# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'chessUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ChessAI(object):
    def setupUi(self, ChessAI):
        ChessAI.setObjectName("ChessAI")
        ChessAI.resize(800, 600)
        ChessAI.setStyleSheet("background-color: white\n"
"")
        self.centralwidget = QtWidgets.QWidget(ChessAI)
        self.centralwidget.setObjectName("centralwidget")
        self.newGame = QtWidgets.QPushButton(self.centralwidget)
        self.newGame.setGeometry(QtCore.QRect(30, 10, 93, 28))
        self.newGame.setStyleSheet("")
        self.newGame.setObjectName("newGame")
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(30, 40, 351, 461))
        self.textBrowser.setObjectName("textBrowser")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(390, 370, 55, 16))
        self.label.setObjectName("label")
        self.statusLabel = QtWidgets.QLabel(self.centralwidget)
        self.statusLabel.setGeometry(QtCore.QRect(440, 370, 341, 21))
        self.statusLabel.setFrameShape(QtWidgets.QFrame.Box)
        self.statusLabel.setObjectName("statusLabel")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(392, 79, 331, 46))
        self.widget.setObjectName("widget")
        self.formLayout = QtWidgets.QFormLayout(self.widget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.recogspeechlabel = QtWidgets.QLabel(self.widget)
        self.recogspeechlabel.setStyleSheet("")
        self.recogspeechlabel.setObjectName("recogspeechlabel")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.recogspeechlabel)
        self.recogspeechsetlabel = QtWidgets.QLabel(self.widget)
        self.recogspeechsetlabel.setObjectName("recogspeechsetlabel")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.recogspeechsetlabel)
        self.skilllevelLabel = QtWidgets.QLabel(self.widget)
        self.skilllevelLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.skilllevelLabel.setObjectName("skilllevelLabel")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.skilllevelLabel)
        ChessAI.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(ChessAI)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        ChessAI.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(ChessAI)
        self.statusbar.setObjectName("statusbar")
        ChessAI.setStatusBar(self.statusbar)

        self.retranslateUi(ChessAI)
        QtCore.QMetaObject.connectSlotsByName(ChessAI)

    def retranslateUi(self, ChessAI):
        _translate = QtCore.QCoreApplication.translate
        ChessAI.setWindowTitle(_translate("ChessAI", "MainWindow"))
        self.newGame.setText(_translate("ChessAI", "New Game"))
        self.label.setText(_translate("ChessAI", "Status"))
        self.statusLabel.setText(_translate("ChessAI", "TextLabel"))
        self.recogspeechlabel.setText(_translate("ChessAI", "Recognized Speech:"))
        self.recogspeechsetlabel.setText(_translate("ChessAI", "TextLabel"))
        self.skilllevelLabel.setText(_translate("ChessAI", "Skill Level:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ChessAI = QtWidgets.QMainWindow()
    ui = Ui_ChessAI()
    ui.setupUi(ChessAI)
    ChessAI.show()
    sys.exit(app.exec_())
